# Site Settings
title:               Lagrange
tagline:             a minimalist Jekyll theme
description:
baseurl:            #"/Lagrange"
url:                #"https://lenpaul.github.io"
github:
  url:               #"https://lenpaul.github.io/Lagrange"
author:
  name:              "Meghana Reddy Guduru"
  email:             "mreddygu@andrew.cmu.edu"
  twitter:           "paululele"
  instagram:         "paululele"
  github:            "lenpaul"
  facebook:          "Le.Paul.94"
  linkedin:          "lenpaul"
navigation:
- title: About
  url: /about
- title: Writing
  url: /writing
- title: Contact
  url: /contact

paginate:            5
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
