# Site Settings
title:               Meghana Reddy
tagline:             a geek at heart
description:
baseurl:            #"/Lagrange"
url:                #"https://lenpaul.github.io"
github:
  url:               #"https://lenpaul.github.io/Lagrange"
author:
  name:              "Meghana Reddy"
  email:             "mreddygu@andrew.cmu.edu"
  twitter:           "meghana734"
  instagram:         "paululele"
  github:            "meghanaguduru"
  facebook:          "meghanakgp"
  linkedin:          "meghanaguduru"
navigation:
- title: About
  url: /about
- title: Writing
  url: /writing
- title: Contact
  url: /contact

paginate:            5
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
